[package]
name = "bhs"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "BHOP script for any game"
repository = "https://github.com/Antosser/bhop-script"
readme = "README.md"

[dependencies]
anyhow = "1.0.79"
inputbot = "0.6.0"
inquire = "0.6.2"
